### ISSUE TITLE
Add Rstudio notebook instructions

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#100]
Probably a link to a good resource is enough.

**Comment by sbfnk** [comment]
@kathsherratt are you happy to do this or should someone else? Can't remember why I ended up (perhaps wrongly) assigning this to you.

We need to combine this with instructions on where people can find session files once they have downloaded / cloned everything. And probably add a bit to the beginning of each session with what the file name is that people need to open?

**Comment by kathsherratt** [comment]
On it
