### ISSUE TITLE
use cmdstanr instead of rstan

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#12]
Do we want to do this to ourselves and our course participants - i.e maybe we bite the small compilation bullet and use `cmdstanr`? The advantage of this potentially is that if they can't install `cmdstan` as a dependency they can still interact with all the material as installing deps won't fail for them?

_Originally posted by @seabbs in https://github.com/nfidd/nfidd/pull/10#discussion_r1582840247_

**Comment by seabbs** [comment]
I think we have agreed that this is a yes?

**Comment by sbfnk** [comment]
yes
