### ISSUE TITLE
ensure we have an R function for every stan function

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#122]
initial feedback indicates that this is very useful

**Comment by seabbs** [comment]
I'm going to lightly pushback on this that in some instances this is quite a lot of work and not really key to teaching the understanding we are going for. For example exactly tracking how the joint nowcast model works isn't critical to learn the lessons we are trying to impart here?

**Comment by sbfnk** [comment]
Yes, that makes sense - will bear in mind when reviewing the nowcasting session in detail but assume for now we only want this for functions we're actually using for simulation.

**Comment by sbfnk** [comment]
I'll have a look at adding this for the random walk

**Comment by seabbs** [comment]
I meant to add a section for the random walk like we have for the AR in the forecasting concepts but likely forgot
