### ISSUE TITLE
Potentially introduce nowcasting stan functions as R functions

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#123]
The other thing we're not doing here is introduce the stan functions as R functions first (which when doing means we can ask people to trust us that we've implemented correctly so they don't have to engage with stan syntax). Something to focus on in #31.

_Originally posted by @sbfnk in https://github.com/nfidd/nfidd/issues/112#issuecomment-2175681105_

**Comment by sbfnk** [comment]
closing in favour of #122
