### ISSUE TITLE
Improving the generative model for the reproduction number could probably do with a slide or two and some discussion of behaviour 

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#124]
Improving the generative model for the reproduction number could probably do with a slide or two and some discussion of behaviour (noise + near-present). This could tie in nicely with the earlier discussion in https://github.com/nfidd/nfidd/blob/c3e6731a178d9dc06a05e05a396a6103d9f33b16/sessions/slides/introduction-to-reproduction-number.qmd#L25 (see also #120)

_Originally posted by @sbfnk in https://github.com/nfidd/nfidd/pull/112#discussion_r1644154497_

**Comment by sbfnk** [comment]
Not doing for same reason as #120 (not straightforward to include in slides)
