### ISSUE TITLE
Add note about inferring I0 to nowcasting session

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#125]
All models that need an initial number infections currently take `I0` as a data input. This wouldn't be available in a real world setting and so I suggest we infer it instead. 

This has been implemented in the joint nowcasting renewal model and seems to work okay.

**Comment by sbfnk** [comment]
I think given time constraints this may have to wait until after the course. What might be nice is to add a little note to the joint nowcasting session saying: see what we did here? We've moved away from this unrealistic assumption.

**Comment by seabbs** [comment]
Agree

**Comment by seabbs** [comment]
@kathsherratt as the only person (I think) not on a plane can you throw in a quick pr here?
