### ISSUE TITLE
Develop and allocate lesson plan

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#13]
At the moment we have clear learning objectives and a nice framework for an individual lesson (i.e the introduction) but no map of how these will be used to make the overall course (especially in the time available). 

It feels like the next step is to agree a time allocation for each section and the time of material that should be in each (i.e lecture or practical etc.) and then allocate these to people to create the material.

**Comment by sbfnk** [comment]
I agree, will share draft imminently.
