### ISSUE TITLE
random walk model for R estimation struggles to fit

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#131]
The estimates are great but the MCMC struggles, sometimes destructively so. Investigating whether any reparametrisation can solve it (quite a bit of correlation between parameters to wreak havoc with HMC).

**Comment by seabbs** [comment]
Just reopening as not absolutely sure this has been resolved. We might want to check explicitly?

**Comment by sbfnk** [comment]
You're right, it hasn't. Still produces >1e10 infections 20% of the time
```
# A tibble: 1 × 5
  approach    num_divergent num_max_treedepth ebfmi crazy_infections
  <chr>               <dbl>             <dbl> <dbl>            <dbl>
1 constrained          8.55              941. 0.920              0.2
```

**Comment by sbfnk** [comment]
Shall we revert to the direct approach in https://github.com/nfidd/nfidd/pull/132 given that at least it never produces crazy trajectories?

**Comment by seabbs** [comment]
I want to distinguish between trajectories that are initially too high and trajectories that are high but within support of the prior. Are we talking about the former?

**Comment by seabbs** [comment]
The other option here if it is initialisation is to supply a reasonable initial condition

**Comment by sbfnk** [comment]
Would a weekly random walk be an option?

**Comment by sbfnk** [comment]
The annoying thing is that the model does work well in principle. It's just unstable, slow and clearly struggles to explore the posterior.

**Comment by seabbs** [comment]
> Would a weekly random walk be an option? 

It would be more performant at the cost of being a bit difficult to communicate. 

The other issue we face is runtime. The current models towards the end of the timeseries are taking > 1 hour fit (on my not that new laptop so that might be part of it)

**Comment by sbfnk** [comment]
That is an issue. Can we provide saved CmdStanFit objects for the slower ones (it's what we do in the mfiidd course)?

Runtimes in the CI seem manageable (20 mins for the whole course last time I checked)

**Comment by seabbs** [comment]
> Can we provide saved CmdStanFit objects for the slower ones (it's what we do in the mfiidd course)?

These are the fits we are giving them the posterior samples of so they should never find this (unless they play around and get themselves in trouble

**Comment by sbfnk** [comment]
> I want to distinguish between trajectories that are initially too high and trajectories that are high but within support of the prior. Are we talking about the former?

I'll try to have a look in an example

**Comment by sbfnk** [comment]
Here's an example

<img width="669" alt="image" src="https://github.com/nfidd/nfidd/assets/1156307/25f08ef3-18b3-486a-a460-b795bfd63ef8">

Maybe setting `init = list(init_R = 0, rw_sd = 0)` would help. Or even just `rw_sd = 0`

**Comment by seabbs** [comment]
> Maybe setting init = list(init_R = 0, rw_sd = 0) would help. Or even just rw_sd = 0

Yeah I think it might. This is really strange behaviour.

**Comment by sbfnk** [comment]
With `init = 0` (i.e. initialise everything to zero) we still get a few of divergent transitions and lots of max treedepth issues but no more crazy trajectories. And ebfmi is high suggesting perhaps that the posterior is being explored even if always starting from the same point.

**Comment by sbfnk** [comment]
The same is true with the original parametrisation so I think the way forward is:
- revert to unconstrained
- init all to 0
- add a fold out explainer that 1) we can do this because all is centred and 2) we do this becuase otherwise the sampler might straggle e.g. if rw_sd is high because high R can very quickly generate so many infections that a small change in parameters won't make a difference (-> numerical instability) and 3) in general is good practice to think about this and the stan dfeault won't necessarily be sensible and 4) ideally we'd start different chains in different places -- or some shorter / better phrased version of this blurb

**Comment by seabbs** [comment]
>  \() list(init_R = 0, rw_sd = 0.01)

I am using this now to update the AR forecasts and its helping a lot

**Comment by sbfnk** [comment]
would `init=0` also work? As elsewhere I think the simpler the better here

**Comment by sbfnk** [comment]
(besides simplicity I think it's justifiable to start exploring from baseline constant R=1)
