### ISSUE TITLE
Feedback: convolution slides need to make more connection to epi

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#140]
- e.g., explain "secondary event" and "primary event"
- why do you need to do a convolution?

would be good to have final figure along the way to indicate what each steps means.

**Comment by sbfnk** [comment]
throughout: connections to outbreak dynamics could be stronger

**Comment by seabbs** [comment]
I read this through again in #187 and I really thought it was fine as is given the context of the earlier sessions. I tried a bit of a reorg and just felt like it was more confusing

**Comment by sbfnk** [comment]
OK, happy for this to be closed
