### ISSUE TITLE
x axis in 1st fig of delay distributions session looks off

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#145]

**Comment by seabbs** [comment]
(a bit vague so I think you might need to do this one!)

**Comment by jamesmbaazam** [comment]
I think I fixed this in https://github.com/nfidd/nfidd/pull/198/. The x-axis was expanding into the negatives without data. See  https://github.com/nfidd/nfidd/blob/4e4d3248f3ec64a7c3f7b76210fd3ee82fd0e756/sessions/delay-distributions.qmd#L73

**Comment by sbfnk** [comment]
There was a weird x axis (I think too many braks potentially). Looking good now.
