### ISSUE TITLE
go through course material and check for wrong references to population sizes

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#154]
also set cutoff to 71

**Comment by seabbs** [comment]
I search for 1000 and N and didn't find any issues

**Comment by seabbs** [comment]
I think only the joint nowcasting session uses a cutoff of 71 everywhere else it is 41 and that is encoded into the text as well. 

Do we want to move the whole course to 41, shift the joint nowcasting session, or leave as is?

**Comment by sbfnk** [comment]
I think move all to 71.

There are also things like these so I think a full-text search might not reveal all (although of course these might actually be the only occurrences).

https://github.com/nfidd/nfidd/blob/e6a10c70ac3683c7ecfd044bf35b38b1f8501b25/sessions/delay-distributions.qmd#L45

https://github.com/nfidd/nfidd/blob/e6a10c70ac3683c7ecfd044bf35b38b1f8501b25/sessions/delay-distributions.qmd#L44

**Comment by seabbs** [comment]
In updating should probably switch to make these be drawn from the data vs written in

**Comment by sbfnk** [comment]
There was a reason not to do this but I can't remember it. Perhaps the difficulty of identifying the peak beyond looking at a plot.

**Comment by seabbs** [comment]
or just makes it hard to read in raw form?

**Comment by sbfnk** [comment]
Yes. And maybe that section really is the only bit as it introduces the data set. And the cutoff.
