### ISSUE TITLE
`set.seed(1234)` for the top of the code?

### ISSUE THREAD

**Issue by toshiakiasakura** [nfidd/nfidd#159]
Minor points. 
I am always assured if prepared pages can be exactly reproduced. 

When I ran the code and displayed values were different from the ones in the web page, I would lose some degree of confidence. So, I prefer to put the `set.seed(1234)` or something like that just after reading libraries to secure the exact reproducibility.

**Comment by sbfnk** [comment]
A seed is already set but this is hidden from the viewer - would indeed be good to expose.
