### ISSUE TITLE
remove coding exercises

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#165]
We only have a few of these in there anyway but I don't think this works with the Rstudio editable notebook set up - it requires people to do things in their own separate R session.

In the model fitting course part of the philosophy is that people should e.g. code their own Metropolis-Hastings algorithm and as a way to reinforce learning - but I have no evidence that it does so.

All that said we definitely don't need people to spend time working out how to round numbers down etc.. In summary let's just give them the code.

**Comment by seabbs** [comment]
I can't see any more of these do we think this is done?
