### ISSUE TITLE
Make the intro to forecasting concepts session match previous sessions

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#172]
Departing from previous sessions where this is repeated so would be good to add a paragraph here (can do in separate issue)

_Originally posted by @sbfnk in https://github.com/nfidd/nfidd/pull/126#discussion_r1648606854_

**Comment by kathsherratt** [comment]
Will be closed with #209

**Comment by seabbs** [comment]
Noting we merged #209 before getting to this so this is still outstanding

**Comment by kathsherratt** [comment]
fixed by #275
