### ISSUE TITLE
Slides: introduction to joint nowcasting (with delays)

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#178]

**Comment by seabbs** [comment]
I can do this one.

**Comment by sbfnk** [comment]
I was going to: 
- show this figure again (linking to previous talk) https://github.com/nfidd/nfidd/blob/main/sessions/slides/figures/germany_historical.png
- show what the reporting triangle is
- that's it (doesn't need many slides I think).

Happy for you to take!!

**Comment by seabbs** [comment]
I don't mind either way but I guess I should do one set of slides. Sounds like a good outline will follow
