### ISSUE TITLE
problems lazy loading package data when using R notebook interactively

### ISSUE THREAD

**Issue by kathsherratt** [nfidd/nfidd#180]
I'm finding that the direct calls to load package data ([eg](https://github.com/nfidd/nfidd/blob/c254b1afa664c57afe634db5d8ce2b522a7d4511/sessions/forecasting-concepts.qmd#L253)) don't always work interactively within R notebooks. 

We could wrap these calls in `data()` to make sure they work consistently? (Personally I also like that this flags clearly that we're loading in new data.) 

If yes I'm happy to do this as I work back through sessions.

**Comment by sbfnk** [comment]
I'm OK with this - could also disable lazy loading to gently enforce this?

**Comment by seabbs** [comment]
I think this has been covered now?
