### ISSUE TITLE
Use onset_df from a snippet everywhere

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#191]
We currently have a package `example_onset_df` and also use `onset_df` as generated by a snippet of code. We should use the same thing everywhere. The only thing we need to watch for is to make sure that the snippet uses a deterministic process to avoid lots of downstream issues.

**Comment by kathsherratt** [comment]
I think we should use `onset_df` (the `example_` only comes up in the later sessions and then felt a bit weird to have been generating it all this time).
