### ISSUE TITLE
Delay distributions slides could benefit from a figure

### ISSUE THREAD

**Issue by jamesmbaazam** [nfidd/nfidd#194]
I think it would be easier to convey the ideas presented in the delay distributions slides as a figure. There are quite a few in the wild that can be re-used here with attribution.

- Examples: 
- https://www.reconlearn.org/slides/outbreak-statistics/outbreak-statistics#14
- https://academic.oup.com/aje/article/158/11/1039/162725?login=false
- https://drive.google.com/file/d/1p4wgQ5AS0S7ZTqPXO5KjDAwA7qNcmXpn/view

**Comment by sbfnk** [comment]
I agree but closing this as not a priority.
