### ISSUE TITLE
Are the priors in the `gamma_model.stan` truncated?

### ISSUE THREAD

**Issue by jamesmbaazam** [nfidd/nfidd#197]
In https://github.com/nfidd/nfidd/blob/459d1bfcc5424a1e36f193ce7a575fc8d7ee48cd/sessions/R-Stan-and-statistical-concepts.qmd#L154, you state that the priors are truncated. I thought they would be if they were defined using `T[]` like here https://github.com/nfidd/nfidd/blob/459d1bfcc5424a1e36f193ce7a575fc8d7ee48cd/stan/lognormal.stan#L14.

**Comment by sbfnk** [comment]
You're right! The truncation should be added to alpha and beta
