### ISSUE TITLE
Explore the performance of the differenced AR

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#206]
As noted in #163 the expectation of using the difference AR was that it would do better during periods of change as it could extrapolate small changes further into time (i.e turnover faster). I think ideally we would investigate this as its a useful teaching point we are currently missing (about mechanism and non-mechanism being able to achieve the same thing)

**Comment by seabbs** [comment]
One explanation could be that the prior for the standard deviation is too tight as it is the same as the random walk version but now being applied on the difference scale.

**Comment by seabbs** [comment]
Still very confused about this. @sbfnk does the code look right to you/any ideas?

**Comment by sbfnk** [comment]
will have a look when in a little bit when I've got slightly more time

**Comment by seabbs** [comment]
I'm also planning on having another crack but I'm concerned I am missing something obvious
