### ISSUE TITLE
What is stan and is it scary - pre-course material

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#21]
As title

**Comment by seabbs** [comment]
Some stuff here: https://package.epinowcast.org/articles/stan-help.html

Need to decide how much should reproduce the lecture and how much not (leaning towards giving slides ahead of time and using the material as a cheat sheet for people to look at throughout thee course if they don't stuck).

**Comment by sbfnk** [comment]
This has a brief lecture now.
