### ISSUE TITLE
Allocate lectures + session "leadership"

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#215]
I think we should have an allocated leader per session and that this should likely be the person who goes through the slides. 

We spoke about @sbfnk and I handing off on this but do we want to write it down explicitly (i.e here) or change that decision up at all. I have no strong preference.

We could also go with whoever wrote the material should give the lecture but that leaves @sbfnk doing all but two (which I am totally happy with and might have consistency benefits but feels unfair even when taking into account their august majesty)

**Comment by sbfnk** [comment]
tentatively (can revisit later) I'm happy with me day 1, you day 2 - i.e. who led writing the sessions.

**Comment by sbfnk** [comment]
This was in terms of session leading, I'm also happy to give all the lectures I drafted you don't want to have to deal with my slides (what a power move to put together all these decks of three slides text only). 

Perhaps we just agree that I start tomorrow and then we see how we go.

**Comment by seabbs** [comment]
>  I'm happy with me day 1, you day 2 - i.e. who led writing the sessions.

Sure
