### ISSUE TITLE
Number of posterior samples for plotting

### ISSUE THREAD

**Issue by kathsherratt** [nfidd/nfidd#217]
Sometimes we plot the whole posterior (eg renewal session), sometimes we sample 100 trajectories (eg convolutions session), sometimes 50 (forecast models session). It's confusing and think we should stay consistent.

**Comment by sbfnk** [comment]
I think downsampling 50 or 100 makes sense, plotting 4000 just shows up as a black blob

**Comment by seabbs** [comment]
The reason it is 100 or 50 is because of their being multiple models in a single plot and it being too heavy at 50. I don't think its a big deal though so fine with whatever we go with as long as the plots don't ages to make!
