### ISSUE TITLE
Material fix prior to tomorrow

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#240]
Flagging we need to freeze material prior to 9am tomorrow as participants who download won't get the updates and if they make any changes to the sessions and we ask them to redownload they will lose them. 

We can make changes that don't touch them (to slides etc)

**Comment by sbfnk** [comment]
Yes I was thinking this was a downside with our current set up (partly due to using interactive notebooks but also use of `here` to load snippets and models). I think this is something to revisit as part of https://github.com/nfidd/nfidd/issues/118
