### ISSUE TITLE
More further reading 

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#246]
On a coach so can't pr myself. 

Jason's paper is a good one for the little bit of mechanism goes a long way

https://pubmed.ncbi.nlm.nih.gov/28342787/

I think we can have one straight up self citation... 

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1006785

Stoner on nowcasting

https://arxiv.org/pdf/1912.05965

**Comment by seabbs** [comment]
Maybe one of Kath's for real world forecast evaluation? Maybe the elife one?

**Comment by sbfnk** [comment]
yep will add all

**Comment by sbfnk** [comment]
> I think we can have one straight up self citation...

They pretty much all have at least one of us on them. But the flipside of that is they're being taught by people who have actually worked on this.
