### ISSUE TITLE
Forecasting plots don't reflect model fit

### ISSUE THREAD

**Issue by zsusswein** [nfidd/nfidd#259]
@seabbs -- throwing this together quickly to link in a PR.

The differenced AR1 model is producing some weird forecasts in the existing qmd:

![image](https://github.com/nfidd/nfidd/assets/46581799/104fe64a-f4c8-4c15-9ab9-728050d0f1b3)

We did some investigating into source. It seemed like it might be a bug in the Stan code, but after some digging we realized that manually created plots out of the fitted model object look fine:

![image](https://github.com/nfidd/nfidd/assets/46581799/913d0e2b-bd58-4aa2-bf13-0a8311dcf5aa)

![image](https://github.com/nfidd/nfidd/assets/46581799/e5f5e886-2948-4ec2-88c6-83d6c060c667)

It looks to me like the issue is in the plotting code in https://github.com/nfidd/nfidd/blob/fa76691ca77eac23f953a6b043624cf0f657d088/sessions/forecasting-models.qmd#L292-L317

I think there's problems (1) the data being compared isn't lining up properly (join issue) (2) the forecast horizon is so long that the AR process is blowing up will make it hard to see.

I'd propose fixing both by changing the draws extraction and join and limiting the plotting to 55 or so days.

**Comment by seabbs** [comment]
Aweoms thanks @zsusswein. 

Did you find any changes to the priors that made a difference with the model performance?

**Comment by seabbs** [comment]
@kathsherratt do you think we have this problem anywhere else? Like in the forecast concepts session?

**Comment by seabbs** [comment]
ah damn. I think its because the output of `gather_draw` is grouped by `day` and that makes the following filter be grouped by day. That then causes a bunch of partial trajectories?

**Comment by seabbs** [comment]
not clear why this would just be happening here vs everywhere?

**Comment by zsusswein** [comment]
> Did you find any changes to the priors that made a difference with the model performance?

I did play around with the model when I was bug-hunting. I was curious if the constraint on the damping would have caused an issue and I thought the total variance was perhaps too high.

![image](https://github.com/nfidd/nfidd/assets/46581799/8a0fa749-f90a-43eb-a833-571d63498edb)

In the posterior, I don't know if I see that having a large impact. The fitted damping value isn't strongly changed nor is the $R_{t = 0}$. The variance change does have an impact, but it's sort of a dealer's choice situation on what you believe is reasonable. I might make it lower in my own work, but I wasn't planning on modifying it here as a bugfix.

![image](https://github.com/nfidd/nfidd/assets/46581799/64ed3650-3999-4d6e-ba5c-9b1bc3f070cd)

**Comment by kathsherratt** [comment]
> not clear why this would just be happening here vs everywhere?

I'll open a PR to ungroup elsewhere (following #263)
