### ISSUE TITLE
statistical vs. more statistical vs. semi-mechanistic

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#288]
There's a bit of mixture of nomenclature between the forecasting models slides and practice session:

slides:
- statistical: ARIMA, stochastic volatility etc., no mechanistic component
- semi-mechanisitic: models that include an epidemiological mechanism such as the renewal equation and combine it with concepts from statistical models, i.e. what we use in the course

practice session:
- we call "statistical" a model with differenced AR on Rt because it contains "more statistical structure" than the random walk (though arguably it's just a different statistical structure). According to the lecture this would be a semi-mechanistic model.

Maybe worth either adding a clarification somewhere or rename the model in the practice session?

**Comment by seabbs** [comment]
Fixed on `main`: [76f6b25](https://github.com/nfidd/nfidd/commit/76f6b257e7a1f615c11e86ce7f21aec53489db3e)
