### ISSUE TITLE
Existing resources

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#3]
We should compile existing open-source resources for teaching the concepts in this course (especially ones using R), as we may  be able to adapt and/or use them.

**Comment by sbfnk** [comment]
- https://github.com/epiforecasts/marburg.parameters has delay estimation in stan
- https://github.com/jbracher/NOZGEKA has a nice introduction to nowcasting and some great exercises

**Comment by sbfnk** [comment]
https://github.com/seabbs/cste-forecasting-workshop

**Comment by seabbs** [comment]
I like this `epinowcast` helper for `stan`: https://package.epinowcast.org/articles/stan-help.html
