### ISSUE TITLE
Add a full ensemble session

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#338]
Might be a bit early to do this but I'd be keen to either do or help make a full session on ensembles (so we cover all the current learning objectives)

**Comment by sbfnk** [comment]
I think this is a good idea (and thanks to @kathsherratt we already have slides), and I don't think we have to wait with developing more material.

What might be good would be to think about how we signpost parts of this in person when we don't teach all of it (as the material is already quite crammed for 2.5 days but we may well teach 2.5 day versions of this in the future.

**Comment by sbfnk** [comment]
This should be addressed as part of #342

**Comment by sbfnk** [comment]
Done in #355
