### ISSUE TITLE
Understanding, evaluating, and improving forecasts of infectious disease burden

### ISSUE THREAD

**Issue by seabbs** [nfidd/nfidd#342]
# In November we are running the following workshop

Predictive modelling of infectious disease dynamics has become increasingly used by public health decision-makers and is a key part of pandemic preparedness efforts. However, the techniques that forecasts rely on remain the domain of specialists. In our work, via mediums such as this workshop, we seek to expand access to these techniques, as well as equip academics and public health institutions with the capacity to make and critically interpret predictions from infectious disease models.

We aim to deliver a workshop that enables participants to understand, evaluate, and improve forecasts of infectious diseases. We will introduce participants to the key elements of making infectious disease forecasts and provide them with the tools to understand broad concepts and approaches to forecasting in infectious disease epidemiology. We will also introduce forecast evaluation by comparing forecasts with what then happened, and explore how this can be used to understand the strengths and limitations of forecasts better. Finally, we will introduce forecast ensembles as a means of combining forecasts from multiple models to produce improved forecasts for use by decision-makers.

We will divide the workshop into short lectures interspersed with interactive practical sessions using the statistical software R. We propose:

- Lecture: Overview of the workshop (5 minutes)

- Lecture: Introducing the forecasting concept (15 minutes)

- Practical: Visualising infectious disease forecasts (30 minutes)

- Lecture: Introduction to forecast evaluation (15 minutes)

- Practical: Evaluating real-time forecasts from a range of infectious disease forecast models (60 minutes)

- Lecture: Introduction to forecast ensembles (15 minutes)

- Practical: Improving real-time forecast performance using ensemble methods (60 minutes)

- Lecture: Summary of the workshop (10 minutes)

Infectious disease forecasts are highly likely to play a role in responding to future outbreaks. Improving the global capacity to produce and critically evaluate these will contribute to better pandemic preparedness and health decision-making.

# Material

Potentially, we can reuse the forecasting concept and forecast evaluation lectures but we may also need new slides. If we do need new slides it might be worth thinking how these would integrate if we taught all the material (both old and new).

We might need to think about how/where we put the summary and overview slides for this single workshop as they will be specific to teaching this vs te full course.

## Lectures

- [ ] Overview
- [ ] Forecasting concept - needs to introduce whatever data the visualisation workshop uses
- [ ] Forecasting evaluation - needs to introduce evaluation in high dimensions (i.e. many models)
- [ ] Ensembles
- [ ] Summary

## Practicals

- [ ] Visualising infectious disease forecasts
- [ ] Evaluating real-time forecasts from a range of infectious disease forecast models
- [ ] Improving real-time forecast performance using ensemble methods

> [!NOTE]
> After discussion I will make new issues for each new piece of material we need and any review we need to do.

**Comment by sbfnk** [comment]
> Potentially, we can reuse the forecasting concept and forecast evaluation lectures but we may also need new slides. If we do need new slides it might be worth thinking how these would integrate if we taught all the material (both old and new).

Perhaps one way to think about this would be to have a "master" course here (with everything) and then any shortened offshoot would live either in a fork or a branch. We could then link to any of these from the landing page. For cleanliness it's probably easier to work in a separate branch rather than a for but this will require a slightly more elaborate GHA set up (which otherwise could just be used as a copy of of actions the main repo).

> We might need to think about how/where we put the summary and overview slides for this single workshop as they will be specific to teaching this vs te full course.

I was thinking we'd have a separate page with its own structure etc so people are only exposed to the full course should they want to have a look (with links / reference at the end).

**Comment by seabbs** [comment]
As a first pass at this I am going to write a ensemble session that builds on the material we already have (so we can give a course) and then if/time write sessions proposed above

**Comment by seabbs** [comment]
Having said that the current ensemble slides are very hub and quantile focussed so I am not sure my proposal really makes a great deal of sense given that.

**Comment by seabbs** [comment]
My revised course suggestion is that we finish work on the ensemble practical in #355  (doing this now) and tune up the forecasting material we have. Once we are happy we set this repo as a template repo and make a new repository for the course. We can then prune to just the material we actually want including shortening the current concepts and forecasts sessions (probably to remove the direct back links and use of the stan models?). 

So this would look like: 

Lecture: Overview of the workshop (5 minutes)

Lecture: Introducing the forecasting concept (15 minutes)

Practical: Evaluate a single forecast (30 minutes)

Lecture: Introduction to forecast evaluation (15 minutes)

Practical: Evaluating real-time forecasts from a range of infectious disease forecast models (60 minutes)

Lecture: Introduction to forecast ensembles (15 minutes)

Practical: Improving real-time forecast performance using ensemble methods (60 minutes)

Lecture: Summary of the workshop (10 minutes)

Its not ideal but I don't really have time this week to write a few more sessions and I looked back at the material and I don't think it will take that much effort to make it stand alone (I also like the lectures as they currently are).

Thoughts?

**Comment by sbfnk** [comment]
I agree, I think between extracting relevant bits from the existing and then the new material there is more than enough content. We just take out the stan models.

Are you happy to do the templating / new repo creation? Otherwise I can look into how to best do it.

**Comment by seabbs** [comment]
Yes. I have all of Monday to work on this but only a few hours here and there before that.

**Comment by sbfnk** [comment]
OK, will see how far I get myself when I've got some time.

**Comment by seabbs** [comment]
Yup sounds good - thanks. I can work through in detail and add optional info (we don't currently do a good job of defining a quantile ensemble or wis for example) etc on Monday

**Comment by seabbs** [comment]
Happy to have a larger section left to me to port as well so no stress if can't get to everything

**Comment by sbfnk** [comment]
Going to close this to continue any discussion over at the other repo.
