### ISSUE TITLE
Make minimum {scoringutils} version clear

### ISSUE THREAD

**Issue by jcken95** [nfidd/nfidd#346]
course relies on development version of {scoringutils} - this could be clearer as many will just install with `install.packages()`

**Comment by seabbs** [comment]
Good point. I think we have been repeatedly overly optimistic about when we are making a release

**Comment by seabbs** [comment]
This can now be bumped to the CRAN version. And the new package approach should hopefully do a better version of helping users get deps.

When we spin versions of the course out as we are doing for idm next week we might want to think about using Renv or similar @sbfnk
