### ISSUE TITLE
typos in {nfidd} install instructions

### ISSUE THREAD

**Issue by jcken95** [nfidd/nfidd#347]
course website states `nfiidd` (two `i`s, no braces) rather than {nfidd}

https://github.com/nfidd/nfidd/blob/2a9c68300ff78ac71fc5e58cb45c3dd379a3a780/getting-set-up.qmd#L40

https://github.com/nfidd/nfidd/blob/2a9c68300ff78ac71fc5e58cb45c3dd379a3a780/getting-set-up.qmd#L42

haven't done a full sweep - but noticed these two :)

**Comment by seabbs** [comment]
Nice thanks for the report! PRs appreciated but no worries will get to it soon.
