### ISSUE TITLE
Practice session: forecasting with a simple model

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#50]
One questions here is what the simple model should be - mentioned ARIMA before but might also be interesting to have e.g. a deterministic SIR model for comparison

**Comment by sbfnk** [comment]
This is the first forecasting session - I think what might be nice here to have a model that puts a quite tight prior on R - e.g. a renewal model with susceptible depletion (which would be close to the simulation model used to generate the time series of infections and nicely bridge to the SIR model that people might know).

**Comment by sbfnk** [comment]
Could maybe introduce it here (in the spirit of gradually increasing complexity of the model)?

**Comment by seabbs** [comment]
The other option is to use the issues with the renewal model as a demonstration of the difference between in sample and real-time performance. i.e go from i.d.d normal -> Random walk to -> difference random walk

**Comment by sbfnk** [comment]
I agree, that is also a nice idea

**Comment by sbfnk** [comment]
Would that also potentially fit in the previous (nowcasting) session?

**Comment by seabbs** [comment]
> Would that also potentially fit in the previous (nowcasting) session?

Yes potentially though there is already quite a bit to handle in that one (i.e the concept of data with more dimensions)

**Comment by seabbs** [comment]
So planning on looking at this tomorrow given #112 and #87 my current plan was to: 

- Use the random walk renewal model to produce some forecasts, visualise and discuss
- Save a bunch of forecasts from this model 
- Use scoring utils to look at evaluating (mainly calibration, bias ec).

**Comment by sbfnk** [comment]
Sounds good!
