### ISSUE TITLE
Practice session: From line list to estimates

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#54]

**Comment by sbfnk** [comment]
Main question here is what data set to use. The Sierra Leone one used in the `epidist` paper is the only published one I know so would be an obvious candidate (but doesn't perhaps have all the features we'd like). Another option would be to simulate one.

**Comment by seabbs** [comment]
I think I am leaning towards simulating one so we can put everything in it we might like.

**Comment by sbfnk** [comment]
Update from call: leaning towards using Sierra Leone example (possibly with some amendments / additions) and no solution provided.
