### ISSUE TITLE
Slides: Introduction to R concepts used in the course

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#57]

**Comment by sbfnk** [comment]
I'm minded to think we won't need this - we could send something like https://github.com/sbfnk/mfiidd/blob/main/docs/rintro.org but really it's silly given how many better intros to R there are on the web.

In the course specs we say that participants

> have basic computer software knowledge  and preferably are familiar with the software R. 
> IMPORTANT: All participants are expected to bring a laptop with R installed on it.

**Comment by seabbs** [comment]
strongly agree. I am tempted towards this for stan as well if we can find a nice intro resource we like

**Comment by sbfnk** [comment]
Yes though that might be harder given that 1) we didn't specify stan as a prerequisite and 2) upon first glance I'm not sure there's an intro resource that uses `cmdstanr`
