### ISSUE TITLE
Slides: An overview of forecasting models

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#70]

**Comment by sbfnk** [comment]
I actually have a half-finished short slide deck for this which I'll finish

**Comment by seabbs** [comment]
ah awesome. I'd forgotten we then needed slides for the new session

**Comment by seabbs** [comment]
Do you want to PR in what you have and I can finish up?

**Comment by sbfnk** [comment]
yes will do within the next 30 mins (no high expectations please)

**Comment by sbfnk** [comment]
we have this now
