### ISSUE TITLE
add howto blurb everywhere

### ISSUE THREAD

**Issue by sbfnk** [nfidd/nfidd#97]
This should be converted to a qmd snippet and then imported everywhere

> Tip
> The code in this session can be run as an interactive notebook using RStudio, or copied-and-pasted into an R session. It needs to be run inside the course repository so that the here() commands below find the stan model files.

**Comment by seabbs** [comment]
I thought about doing this. The only reason I didn't is as is it means the raw notebook is very readable. As people may be working from this it could be worth the duplication.

**Comment by sbfnk** [comment]
If doing this will want to check it doesn't mess with interactive R notebooks.

**Comment by sbfnk** [comment]
It probably makes more sense to remove the blurbs and just ask people to use the visual editor in RStudio. This means we have to tell people where exactly the session files live / what they're called.
